### ISSUE TITLE
Missing object-scan

### ISSUE THREAD

**Issue by simlu** [leinelissen/json-selector-benchmark#1]
Nice job on implementing this! Would be great if you could add [object-scan](https://www.npmjs.com/package/object-scan) to this suite!

_Disclaimer: I'm the author_

**Comment by leinelissen** [comment]
Hey @simlu. Thanks for the suggestion! `object-scan` is now included and released as version 1.0.1.

**Comment by simlu** [comment]
Great, thank you!
